apiVersion: v1
kind: Service
metadata:
  name: master-${cluster_name}-${ pool_index }
  namespace: ${ cluster_namespace }
spec:
  selector:
    vm.kubevirt.io/name: master-${cluster_name}-${ pool_index }
  ports:
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22
    - name: k8s-api
      protocol: TCP
      port: 6443
      targetPort: 6443
  type: LoadBalancer
