apiVersion: v1
kind: Service
metadata:
  name: worker-${cluster_name}-${ pool_index }
  namespace: ${ cluster_namespace }
spec:
  selector:
    vm.kubevirt.io/name: worker-${cluster_name}-${ pool_index }
  ports:
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22
    - name: ingress-http
      protocol: TCP
      port: 80
      targetPort: 30080
    - name: ingress-https
      protocol: TCP
      port: 443
      targetPort: 30443
  type: LoadBalancer
